# application.yml
spring:
  sleuth:
    integration:
      enabled: false
    scheduled:
      enabled: false
    sampler:
      percentage: 1.0
  datasource:
    url: jdbc:mysql://ysql.training:3306/anager_serice?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: choerodon
server:
  port: 20606
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    metadata-map:
      VERSION: v1
  client:
    serviceUrl:
      defaultZone: http://register-server.training:8000/eureka/
    registryFetchIntervalSeconds: 10
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration: # 数据库下划线转驼峰配置
    mapUnderscoreToCamelCase: true
hand:
  name: 朱忠颖
  id: 20606
